---


- name: Clone repository to userhome
  git:
    repo: "{{ dehydrated_repourl }}"
    dest: "{{ dehydrated_userhome }}/dehydrated"
    version: "{{ dehydrated_commit }}"
    # force is needed for unmerged/unreleased bugfix
    # https://github.com/ansible/ansible-modules-core/pull/3416
    force: true
