---

- name: Install required packages
  apt:
    package: "{{ item }}"
    state: present
  with_items:
  - openssl
  - curl
  - sed
  - grep
  - mktemp
  - git


- name: Create user for {{ lcsh_username }}.
  user:
    name: "{{ lcsh_username }}"
    home: "{{ lcsh_userhome }}"
    group: "{{ lcsh_webgoup }}"

- name: Clone repository to userhome.
  git:
    repo: "{{ lcsh_repourl }}"
    dest: "{{ lcsh_userhome }}/letsencrypt.sh"
    version: "{{ lcsh_commit }}"

- name: Create configuration directory {{ lcsh_configdir }}.
  file:
    path: "{{ lcsh_configdir }}"
    state: directory
    owner: "{{ lcsh_username }}"
    group: "{{ lcsh_webgoup }}"
    mode: 0750

- name: Create domain configuration file.
  copy:
    content: "{{ domanins | mandatory }}"
    dest: "{{ lcsh_configdir }}/domains.txt"
  become_user: "{{ lcsh_username }}"


- name: Copy config.sh example to configuration directory.
  copy:
    src: "{{ lcsh_userhome }}/letsencrypt.sh/config.sh.example"
    dest: "{{ lcsh_configdir }}/config.sh"
    remote_src: true
    force: false
  become_user: "{{ lcsh_username }}"

- name: Set BASEDIR value to lcsh_configdir value.
  lineinfile:
    dest: "{{ lcsh_configdir }}/config.sh"
    regexp: "^#?BASEDIR"
    line: "BASEDIR=\"{{ lcsh_configdir }}\""

- name: Set WELLKNOWN value to lcsh_challengesdir value.
  lineinfile:
    dest: "{{ lcsh_configdir }}/config.sh"
    regexp: "^#?WELLKNOWN"
    line: "WELLKNOWN=\"{{ lcsh_challengesdir }}\""

- name: Set CONTACT_EMAIL value to lcsh_contactemail value.
  lineinfile:
    dest: "{{ lcsh_configdir }}/config.sh"
    regexp: "^#?CONTACT_EMAIL"
    line: "CONTACT_EMAIL=\"{{ lcsh_contactemail | mandatory }}\""

- name: Set path to certificate authority.
  lineinfile:
    dest: "{{ lcsh_configdir }}/config.sh"
    regexp: "^#?CA"
    line: "CA=\"{{ lcsh_acme_api }}\""


- name: Create acme-challenges directory {{ lcsh_challengesdir }}.
  file:
    path: "{{ lcsh_challengesdir }}"
    state: directory
    owner: "{{ lcsh_username }}"
    group: "{{ lcsh_webgoup }}"
    mode: 0750


- name: Add cron script for regularly renewals.
  template:
    src: cron_letsencrypt.sh.j2
    dest: /etc/cron.weekly/letsencrypt.sh
    mode: 0700
