---
- etckeeper: action=begin


- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - bash
  - curl
  - git
  - grep
  - mktemp
  - openssl
  - sed


- etckeeper: "action=commit msg='ansible: {{ vars['role_name']}}.packages' rev={{ revision }}"
